name: SOXL Alert

on:
  schedule:
    - cron: '5 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Packages
        run: |
          pip install yfinance pandas requests

      - name: Run Bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          python soxl_alert.py

      - name: Commit State
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git add state.json

          git diff --cached --quiet || \
          git commit -m "Update state"

          git push
